In [30]:
# for dataset https://www.kaggle.com/datasets/pratyushpuri/online-furniture-orders-delivery-and-assembly-2025

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import missingno as msno

In [32]:
df = pd.read_csv("online_furniture_retailer.csv")

In [33]:
df.head()

,product_category,product_subcategory,brand,delivery_status,assembly_service_requested,payment_method,order_id,customer_id,product_price,shipping_cost,assembly_cost,total_amount,delivery_window_days,customer_rating
0,Outdoor,Patio Set,World Market,Failed Delivery,True,Credit Card,93810,2824,191.27,45.63,86.82,323.72,11,3.2
1,Living Room,Sofa,West Elm,Cancelled,True,Apple Pay,13278,5506,702.87,52.65,183.07,938.59,10,4.5
2,Dining Room,Bar Stool,Ashley Furniture,Delivered,False,Cash on Delivery,42098,4657,395.41,96.79,0.00,492.20,2,NaN
3,Dining Room,China Cabinet,HomeGoods,Pending,False,Google Pay,28289,2679,602.59,0.00,0.00,602.59,9,NaN
4,Dining Room,China Cabinet,CB2,Pending,True,Apple Pay,98696,9935,1782.36,69.23,41.53,1893.12,13,1.3

In [34]:
df.drop("order_id" , axis = 1 , inplace=True)
df.drop("customer_id" , axis = 1 , inplace=True)

In [35]:
df.head()

,product_category,product_subcategory,brand,delivery_status,assembly_service_requested,payment_method,product_price,shipping_cost,assembly_cost,total_amount,delivery_window_days,customer_rating
0,Outdoor,Patio Set,World Market,Failed Delivery,True,Credit Card,191.27,45.63,86.82,323.72,11,3.2
1,Living Room,Sofa,West Elm,Cancelled,True,Apple Pay,702.87,52.65,183.07,938.59,10,4.5
2,Dining Room,Bar Stool,Ashley Furniture,Delivered,False,Cash on Delivery,395.41,96.79,0.00,492.20,2,NaN
3,Dining Room,China Cabinet,HomeGoods,Pending,False,Google Pay,602.59,0.00,0.00,602.59,9,NaN
4,Dining Room,China Cabinet,CB2,Pending,True,Apple Pay,1782.36,69.23,41.53,1893.12,13,1.3

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1938 entries, 0 to 1937
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_category            1938 non-null   object
 1   product_subcategory         1938 non-null   object
 2   brand                       1842 non-null   object
 3   delivery_status             1938 non-null   object
 4   assembly_service_requested  1938 non-null   bool
 5   payment_method              1938 non-null   object
 6   product_price               1938 non-null   float64
 7   shipping_cost               1880 non-null   float64
 8   assembly_cost               1900 non-null   float64
 9   total_amount                1938 non-null   float64
 10  delivery_window_days        1938 non-null   int64
 11  customer_rating             1658 non-null   float64
dtypes: bool(1), float64(5), int64(1), object(5)
memory usage: 168.6+ KB

In [37]:
df.isna().sum()

product_category                0
product_subcategory             0
brand                          96
delivery_status                 0
assembly_service_requested      0
payment_method                  0
product_price                   0
shipping_cost                  58
assembly_cost                  38
total_amount                    0
delivery_window_days            0
customer_rating               280
dtype: int64

In [38]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
product_price,1938.0,1155.930026,658.490908,81.43,609.2425,1076.230,1628.550,2979.56
shipping_cost,1880.0,69.622250,47.555003,0.00,32.5850,74.055,107.735,150.00
assembly_cost,1900.0,62.698137,82.552601,0.00,0.0000,26.285,106.115,299.35
total_amount,1938.0,1288.390010,669.228652,146.93,722.7075,1224.175,1758.500,3093.29
delivery_window_days,1938.0,7.528380,3.987004,1.00,4.0000,8.000,11.000,14.00
customer_rating,1658.0,3.059047,1.152078,1.00,2.1000,3.100,4.000,5.00

In [39]:
df["shipping_cost"].fillna(df["shipping_cost"].mean(), inplace=True)
df["assembly_cost"].fillna(df["assembly_cost"].mean(), inplace=True)
df["customer_rating"].fillna(df["customer_rating"].mean(), inplace=True)

/tmp/ipython-input-1805394790.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["shipping_cost"].fillna(df["shipping_cost"].mean(), inplace=True)
/tmp/ipython-input-1805394790.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["assembly_cost"].fillna(df["assembly_cost"].mean(), inplace=True)
/tmp/ipython-input-1805394790.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["customer_rating"].fillna(df["customer_rating"].mean(), inplace=True)

In [40]:
df.isna().sum()

product_category               0
product_subcategory            0
brand                         96
delivery_status                0
assembly_service_requested     0
payment_method                 0
product_price                  0
shipping_cost                  0
assembly_cost                  0
total_amount                   0
delivery_window_days           0
customer_rating                0
dtype: int64

In [41]:
df.head()

,product_category,product_subcategory,brand,delivery_status,assembly_service_requested,payment_method,product_price,shipping_cost,assembly_cost,total_amount,delivery_window_days,customer_rating
0,Outdoor,Patio Set,World Market,Failed Delivery,True,Credit Card,191.27,45.63,86.82,323.72,11,3.200000
1,Living Room,Sofa,West Elm,Cancelled,True,Apple Pay,702.87,52.65,183.07,938.59,10,4.500000
2,Dining Room,Bar Stool,Ashley Furniture,Delivered,False,Cash on Delivery,395.41,96.79,0.00,492.20,2,3.059047
3,Dining Room,China Cabinet,HomeGoods,Pending,False,Google Pay,602.59,0.00,0.00,602.59,9,3.059047
4,Dining Room,China Cabinet,CB2,Pending,True,Apple Pay,1782.36,69.23,41.53,1893.12,13,1.300000

In [42]:
df["brand"] = df["brand"].fillna(df["brand"].mode()[0] )

In [43]:
df.isna().sum()

product_category              0
product_subcategory           0
brand                         0
delivery_status               0
assembly_service_requested    0
payment_method                0
product_price                 0
shipping_cost                 0
assembly_cost                 0
total_amount                  0
delivery_window_days          0
customer_rating               0
dtype: int64

In [44]:
df["product_category"].value_counts()

product_category
Outdoor        338
Living Room    333
Office         324
Kitchen        322
Bedroom        318
Dining Room    303
Name: count, dtype: int64

In [45]:
df["product_subcategory"].value_counts()

product_subcategory
Bar Cart            90
Pantry Cabinet      87
Garden Chair        80
Kitchen Cabinet     75
Office Chair        73
Dining Chair        72
Lounge Chair        71
Desk                70
Kitchen Island      70
Outdoor Table       69
Bookshelf           69
Dining Table        66
Umbrella            65
Sofa                63
Mattress            62
China Cabinet       61
Buffet              60
Computer Table      59
Ottoman             58
TV Stand            57
Dresser             55
Patio Set           53
Side Table          53
Filing Cabinet      53
Nightstand          53
Coffee Table        52
Bed Frame           51
Armchair            50
Chest of Drawers    50
Wardrobe            47
Bar Stool           44
Name: count, dtype: int64

In [46]:
df["delivery_status"].value_counts()

delivery_status
Delivered          344
Failed Delivery    326
Pending            319
Cancelled          318
In Transit         316
Rescheduled        315
Name: count, dtype: int64

In [47]:
df["payment_method"].value_counts()

payment_method
Credit Card         302
Apple Pay           293
Cash on Delivery    287
Debit Card          287
Google Pay          272
Bank Transfer       257
PayPal              240
Name: count, dtype: int64

In [48]:
df["brand"].value_counts()

brand
Overstock           264
HomeGoods           165
World Market        160
CB2                 154
IKEA                154
West Elm            153
Pottery Barn        153
Ashley Furniture    152
Urban Outfitters    149
Crate & Barrel      146
Wayfair             145
Target              143
Name: count, dtype: int64

In [49]:
df.head()

,product_category,product_subcategory,brand,delivery_status,assembly_service_requested,payment_method,product_price,shipping_cost,assembly_cost,total_amount,delivery_window_days,customer_rating
0,Outdoor,Patio Set,World Market,Failed Delivery,True,Credit Card,191.27,45.63,86.82,323.72,11,3.200000
1,Living Room,Sofa,West Elm,Cancelled,True,Apple Pay,702.87,52.65,183.07,938.59,10,4.500000
2,Dining Room,Bar Stool,Ashley Furniture,Delivered,False,Cash on Delivery,395.41,96.79,0.00,492.20,2,3.059047
3,Dining Room,China Cabinet,HomeGoods,Pending,False,Google Pay,602.59,0.00,0.00,602.59,9,3.059047
4,Dining Room,China Cabinet,CB2,Pending,True,Apple Pay,1782.36,69.23,41.53,1893.12,13,1.300000

In [50]:
df.head()

,product_category,product_subcategory,brand,delivery_status,assembly_service_requested,payment_method,product_price,shipping_cost,assembly_cost,total_amount,delivery_window_days,customer_rating
0,Outdoor,Patio Set,World Market,Failed Delivery,True,Credit Card,191.27,45.63,86.82,323.72,11,3.200000
1,Living Room,Sofa,West Elm,Cancelled,True,Apple Pay,702.87,52.65,183.07,938.59,10,4.500000
2,Dining Room,Bar Stool,Ashley Furniture,Delivered,False,Cash on Delivery,395.41,96.79,0.00,492.20,2,3.059047
3,Dining Room,China Cabinet,HomeGoods,Pending,False,Google Pay,602.59,0.00,0.00,602.59,9,3.059047
4,Dining Room,China Cabinet,CB2,Pending,True,Apple Pay,1782.36,69.23,41.53,1893.12,13,1.300000

In [51]:
import pandas as pd

# Create a pivot table
summary = pd.DataFrame({
    "dtype": df.dtypes,                           # column type
    "unique_count": df.nunique(),                 # number of unique values
    "null_count": df.isnull().sum(),              # number of nulls
})

#dtype can be filtered to see str ones separately

summary["is_string"] = summary["dtype"] == "object"

print(summary)

                              dtype  unique_count  null_count  is_string
product_category             object             6           0       True
product_subcategory          object            31           0       True
brand                        object            12           0       True
delivery_status              object             6           0       True
assembly_service_requested     bool             2           0      False
payment_method               object             7           0       True
product_price               float64          1933           0      False
shipping_cost               float64          1367           0      False
assembly_cost               float64           941           0      False
total_amount                float64          1930           0      False
delivery_window_days          int64            14           0      False
customer_rating             float64            42           0      False

In [52]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

# 1) Columns to which One Hot will be applied
ohe_cols = ["product_category", "delivery_status" , "payment_method" ]
df_encoded = pd.get_dummies(df_encoded, columns=ohe_cols, drop_first=True)

# 2) Columns to be Frequency Encoded
freq_cols = ["product_subcategory", "brand"]
for col in freq_cols:
    freq = df[col].value_counts()
    df_encoded[col] = df[col].map(freq)

# 3) Label Encoding if necessary
le = LabelEncoder()
df_encoded["assembly_service_requested"] = le.fit_transform(df["assembly_service_requested"])

In [53]:
df_encoded.head()

,product_subcategory,brand,assembly_service_requested,product_price,shipping_cost,assembly_cost,total_amount,delivery_window_days,customer_rating,product_category_Dining Room,...,delivery_status_Failed Delivery,delivery_status_In Transit,delivery_status_Pending,delivery_status_Rescheduled,payment_method_Bank Transfer,payment_method_Cash on Delivery,payment_method_Credit Card,payment_method_Debit Card,payment_method_Google Pay,payment_method_PayPal
0,53,160,1,191.27,45.63,86.82,323.72,11,3.200000,False,...,True,False,False,False,False,False,True,False,False,False
1,63,153,1,702.87,52.65,183.07,938.59,10,4.500000,False,...,False,False,False,False,False,False,False,False,False,False
2,44,152,0,395.41,96.79,0.00,492.20,2,3.059047,True,...,False,False,False,False,False,True,False,False,False,False
3,61,165,0,602.59,0.00,0.00,602.59,9,3.059047,True,...,False,False,True,False,False,False,False,False,True,False
4,61,154,1,1782.36,69.23,41.53,1893.12,13,1.300000,True,...,False,False,True,False,False,False,False,False,False,False

In [54]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1938 entries, 0 to 1937
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   product_subcategory              1938 non-null   int64
 1   brand                            1938 non-null   int64
 2   assembly_service_requested       1938 non-null   int64
 3   product_price                    1938 non-null   float64
 4   shipping_cost                    1938 non-null   float64
 5   assembly_cost                    1938 non-null   float64
 6   total_amount                     1938 non-null   float64
 7   delivery_window_days             1938 non-null   int64
 8   customer_rating                  1938 non-null   float64
 9   product_category_Dining Room     1938 non-null   bool
 10  product_category_Kitchen         1938 non-null   bool
 11  product_category_Living Room     1938 non-null   bool
 12  product_category_Office          1938 non-null   bool
 13  product_category_Outdoor         1938 non-null   bool
 14  delivery_status_Delivered        1938 non-null   bool
 15  delivery_status_Failed Delivery  1938 non-null   bool
 16  delivery_status_In Transit       1938 non-null   bool
 17  delivery_status_Pending          1938 non-null   bool
 18  delivery_status_Rescheduled      1938 non-null   bool
 19  payment_method_Bank Transfer     1938 non-null   bool
 20  payment_method_Cash on Delivery  1938 non-null   bool
 21  payment_method_Credit Card       1938 non-null   bool
 22  payment_method_Debit Card        1938 non-null   bool
 23  payment_method_Google Pay        1938 non-null   bool
 24  payment_method_PayPal            1938 non-null   bool
dtypes: bool(16), float64(5), int64(4)
memory usage: 166.7 KB

In [55]:
for col in df_encoded.select_dtypes(include="bool"):
    df_encoded[col] = df_encoded[col].astype(int)

In [56]:
df["total_amount"].describe()

count    1938.000000
mean     1288.390010
std       669.228652
min       146.930000
25%       722.707500
50%      1224.175000
75%      1758.500000
max      3093.290000
Name: total_amount, dtype: float64

In [57]:
df_encoded.head()

,product_subcategory,brand,assembly_service_requested,product_price,shipping_cost,assembly_cost,total_amount,delivery_window_days,customer_rating,product_category_Dining Room,...,delivery_status_Failed Delivery,delivery_status_In Transit,delivery_status_Pending,delivery_status_Rescheduled,payment_method_Bank Transfer,payment_method_Cash on Delivery,payment_method_Credit Card,payment_method_Debit Card,payment_method_Google Pay,payment_method_PayPal
0,53,160,1,191.27,45.63,86.82,323.72,11,3.200000,0,...,1,0,0,0,0,0,1,0,0,0
1,63,153,1,702.87,52.65,183.07,938.59,10,4.500000,0,...,0,0,0,0,0,0,0,0,0,0
2,44,152,0,395.41,96.79,0.00,492.20,2,3.059047,1,...,0,0,0,0,0,1,0,0,0,0
3,61,165,0,602.59,0.00,0.00,602.59,9,3.059047,1,...,0,0,1,0,0,0,0,0,1,0
4,61,154,1,1782.36,69.23,41.53,1893.12,13,1.300000,1,...,0,0,1,0,0,0,0,0,0,0

In [58]:
X = df_encoded.drop("total_amount" , axis = 1).values
y = df_encoded["total_amount"].values

In [59]:
#if with Cross-Validation
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# ------------------------------
# 1. Train-Test Split
# ------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ------------------------------
# 2. Choose Model (Random Forest here, or you can use LinearRegression)
# ------------------------------
model = RandomForestRegressor(random_state=42)
# model = LinearRegression()

# ------------------------------
# 3. Cross-Validation (only on training set)
# ------------------------------
cv_r2_scores = cross_val_score(model, X_train, y_train, cv=5, scoring="r2")
cv_mae_scores = cross_val_score(model, X_train, y_train, cv=5, scoring="neg_mean_absolute_error")
cv_rmse_scores = cross_val_score(model, X_train, y_train, cv=5, scoring="neg_root_mean_squared_error")

print("CV R² scores:", cv_r2_scores)
print("Average CV R²:", np.mean(cv_r2_scores))

print("Average CV MAE:", -np.mean(cv_mae_scores))
print("Average CV RMSE:", -np.mean(cv_rmse_scores))

# ------------------------------
# 4. Train Final Model and Evaluate on Test Set
# ------------------------------
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("\n📊 Test Results")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.3f}")

CV R² scores: [0.99653098 0.99678821 0.99641288 0.99717893 0.99652812]
Average CV R²: 0.9966878219864375
Average CV MAE: 26.62331464516136
Average CV RMSE: 38.34275693577291

📊 Test Results
MAE: 25.89
RMSE: 38.12
R²: 0.997

In [60]:
# without Cross-Validation (if you want to use to with Cross-Validation then no need the use rest of this code)
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [61]:
x_train_max = np.max(X_train)
x_train_min = np.min(X_train)
X_train = (X_train - x_train_min) / (x_train_max - x_train_min)
X_test = (X_test - x_train_min) / (x_train_max - x_train_min)

In [62]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [63]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE (Mutlak Hata): {mae:.2f}")
print(f"MSE (Karesel Hata): {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R² (Doğruluk): {r2:.3f}")

MAE (Mutlak Hata): 25.68
MSE (Karesel Hata): 1357.29
RMSE: 36.84
R² (Doğruluk): 0.997

In [64]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)


mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
nrmse = rmse / np.mean(y_test) * 100

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.3f}")
print(f"MAPE: {mape:.2f}%")
print(f"NRMSE: {nrmse:.2f}%")

MAE: 25.68
MSE: 1357.29
RMSE: 36.84
R²: 0.997
MAPE: 2.41%
NRMSE: 2.84%